package windows;

import javax.swing.Timer;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public class Windows extends javax.swing.JFrame {

    /**
     * Constructor: This runs automatically when the application starts
     */
    public Windows() {
        // 1. Initialize all UI components created by NetBeans (Must be the first line!)
        initComponents(); 
        
        // 2. Set the custom DesktopPanel as the background content pane to show the wallpaper
        DesktopPanel desktop = new DesktopPanel();
        this.setContentPane(desktop);
        
        // 3. Window settings: Center the window on the screen and lock the size
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        // 4. Audio: Play the startup sound from the resources package
        AudioManager.playSound("/windows/resources/openwindows.wav");
        
        // 5. Clock: Start the real-time digital clock timer
        startClock();
    }

    /**
     * Timer logic to update the clock every 1000 milliseconds (1 second)
     */
    private void startClock() {
        // Create a Swing Timer that triggers an action every 1 second
        Timer timer = new Timer(1000, e -> {
            // Get the current system time from the computer
            LocalTime now = LocalTime.now();
            // Set the time format to Hour:Minute:Second
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
            
            // Display the formatted time on your lblClock label
            lblClock.setText(now.format(formatter)); 
        });
        
        // Start the timer running
        timer.start(); 
    }

    /**
     * Component initialization generated by NetBeans.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        // NetBeans will handle the layout and setup inside here automatically
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retro Windows OS");
        
        // Basic layout container initialization
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE) // Set default window width to 1024
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE) // Set default window height to 720
        );

        pack();
    }
    // </editor-fold>                        

    /**
     * The main entry point of the OS application
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            // Open and display the main Windows OS frame
            new Windows().setVisible(true); 
        });
    }

    // Variables declaration - manually added to fix compilation errors
    private javax.swing.JLabel lblClock;
}